### ISSUE TITLE
Speech to text backend

### ISSUE THREAD

**Issue by mretzinger** [sparc-coop/ibis#15]

**Comment by cjoy-ant** [comment]
![image](https://user-images.githubusercontent.com/72472808/162494789-1d1f89d2-065f-4721-bf4a-e995a46b6b8b.png)

### SPEECH-TO-TEXT (microphone)
**Current user flow:**
-User clicks microphone button to trigger Api/TranscribeSpeech and IbisEngine.TranscribeSpeechFromMicrophone()
-User speaks into microphone and SpeechRecognizer.RecognizeOnceAsync() captures speech input until there is a long pause
-Result.Text is saved to Message.Text and added as a message to the conversation

**Changes to make:**
-Allow for continuous speech (e.g., using StartContinuousRecognitionAsync and StopContinuousRecognitionAsync)
-User clicks microphone button and waits for indication to start (beep sound + text "e.g., start your voice message...")
-User clicks micrphone button to stop recording
-Text is shown to user for approval and option to edit before it is saved as Message.Text and sent to the conversation

### SPEECH-TO-TEXT (upload)
**Current user flow:**
-User upload file input located below conversation box to choose local file to upload
-User clicks upload button to trigger Api/UploadFile and IbisEngine.UploadFileAndTranscribe()
-File is saved to Azure blob storage and passed as AudioConfig to SpeechRecognizer.RecognizeOnceAsync()
-Result.Text is saved as Message.Text
-Message currently not populating to conversation automatically, but appears on page refresh

**Changes to make:**
-Consider file size limits
-Allow for video upload and transcription
-Add upload icon back into "options" div and have pop-up modal for upload file input
-Text is shown to user for approval and option to edit before it is saved as Message.Text and sent to the conversation
