### ISSUE TITLE
Speech to text upload edit and modal

### ISSUE THREAD

**Issue by mretzinger** [sparc-coop/ibis#32]

**Comment by cjoy-ant** [comment]
https://github.com/sparc-coop/ibis/tree/feature/speech-to-text

### UPLOAD User Flow:
- Click upload icon
- Upload modal opens
- Choose WAV file
- Click upload button
- WAV file is transcribed
- ConfirmOrEditText modal opens
- Click send button: uploads audio to Azure storage, sets AudioId, sets Text, saves and adds message to conversation
- If message is modified before sending: uploads audio to Azure storage, sets AudioId, synthesizes new speech for ModifiedText, uploads ModifiedAudio to Azure storage, sets ModifiedText sets ModifiedAudioId, saves and adds message to conversation
- Upload / edit modals are closed and conversation is refreshed
- If cancel button is clicked at any point before the message is sent, the message is delted (Api/DeleteMessage) and the files are not uploaded to Azure
