### ISSUE TITLE
Research transcription options and see if azure has improved

### ISSUE THREAD

**Issue by mretzinger** [sparc-coop/ibis#4]

**Comment by cjoy-ant** [comment]
[Azure | Cognitive Services | Speech Services | Speech to Text](https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/)
Features

- High-quality transcription
- Customizable models
- Flexible deployment
- Production-ready
- Multi-language support

Services

- **Accurately transcribe speech from various sources**
    
    Convert audio to text from a range of sources, including microphones, audio files, and blob storage. Use speaker diarisation to determine who said what and when. Get readable transcripts with automatic formatting and punctuation.
    
- **Customize speech models to your needs**
    
    Tailor your speech models to understand organization- and industry-specific terminology. Overcome speech recognition barriers such as background noise, accents, or unique vocabulary. Customize your models by uploading audio data and transcripts. Automatically generate custom models using Office 365 data to optimize speech recognition accuracy for your organization.
    
- **Deploy anywhere**
    
    Run Speech to Text wherever your data resides. Build speech applications that are optimized for robust cloud capabilities and on-premises using containers.
    
- **Comprehensive privacy and security**
    - Speech service, part of Azure Cognitive Services, is certified by SOC, FedRAMP, PCI DSS, HIPAA, HITECH, and ISO.
    - Your data remains yours. Your audio input and transcription data aren't logged during audio processing.
    - View and delete your custom speech data and models at any time. Your data is encrypted while it's in storage.
    - Backed by Azure infrastructure, Speech service offers enterprise-grade security, availability, compliance, and manageability.

[Azure Speech to Text Pricing](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/speech-services/)
Pay as you go | Speech to text
- Standard: $1 per audio hour
- Custom: $1.40 per audio hour
    - Endpoint hosting: $0.0538 per model per hour

***
[GitHub | MicrosoftDocs | azure-docs | Speech Service Overview](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/cognitive-services/Speech-Service/overview.md)

***
[PeerSpot | Best Speech-To-Text Services tools](https://www.peerspot.com/categories/speech-to-text-services)
1. Amazon Transcribe
2. Microsoft Azure Speech Service
3. IBM Watson Speech to Text
4. Google Cloud Speech-to-Text
5. Rev.ai
6. Verbit

***
[TechRadar | Microsoft Azure Speech to Text review](https://www.techradar.com/reviews/microsoft-azure-speech-to-text-review)
- Verdict: 4 stars
- Microsoft’s voice-to-text technology has come a long way, and you can capitalize on its advances by integrating the Azure speech service into your system. That said, price and the need to have a competent Azure cloud developer on staff means Azure certainly isn’t for everyone.
- Pros:
    - Accurate voice analysis that improves with custom speech models
    - Can be run locally to safeguard voice data security
- Cons:
    - Complicated to set up

***
[CompareCamp | Microsoft Azure Speech Services Review](https://comparecamp.com/microsoft-azure-speech-services-review-pricing-pros-cons-features/)
![Score](https://user-images.githubusercontent.com/72472808/157311774-400995b0-8c0f-4255-b015-af1be0f71e47.png)

***
[G2 | Azure Text to Speech API Reviews & Product Details](https://www.g2.com/products/azure-text-to-speech-api/reviews)
![Review](https://user-images.githubusercontent.com/72472808/157311905-dce5acee-3356-43b3-b2a2-9438c328603c.png)
![Review](https://user-images.githubusercontent.com/72472808/157311945-78330e3a-6bbd-4275-95dd-ea570525bcb6.png)
